### ISSUE TITLE
Text Under Dutifulness Wrong

### ISSUE THREAD

**Issue by Nokeo08** [maccyber/bigfive-web#4]
The text on the results page under dutifulness is the same as the text for altruism.

[Altruism](http://i.imgur.com/6HXusMJ.png)
[Dutifulness](http://i.imgur.com/Zb5RAZ2.png)

**Comment by maccyber** [comment]
Slowly done with https://github.com/maccyber/micro-bigfive-results/commit/84bc9348ea8d07b82b8f14c77e93cb9d3dd3ba2d
