### ISSUE TITLE
'generator.bigfive.world' is down

### ISSUE THREAD

**Issue by brianbaso** [maccyber/bigfive-web#7]
How may I get the results to generate and display with 'generator.bigfive.world' down? I tried running the generator micro api on my local machine and then routing the config/index.js file to the port I had it up on but had no success.

**Comment by maccyber** [comment]
Hello @brianbaso!

Sorry for the late answer. I'm currently (slow-) working on a total refactor, see https://github.com/Alheimsins/bigfive-web for code.

@zrrrzzt also have some working code at https://github.com/zrrrzzt/b5-web

**Comment by zrrrzzt** [comment]
@brianbaso You can see the b5-web in action at https://b5.allthethings.win
This is an attempt to make everything run from a static site.

**Comment by brianbaso** [comment]
Ok great, thanks for the insights 👍

**Comment by maccyber** [comment]
http://bigfive-test.com is btw up and working now, the code is still a mess though.
Feel free to test and bring me issues :)
